/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package learn.kotlin.dsl

import java.time.LocalDate

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

val ago = "ago"

infix fun Int.days(tense: String) {
    when(tense) {
        ago -> println(LocalDate.now().minusDays(this.toLong()))
        else -> println("")
    }
}

fun main(args: Array<String>) {
    println(App().greeting)

    call { name ->
        println("${this.toUpperCase()} $name")
    }

    2 days ago
}

fun call(greet: String.(String) -> Unit) {
    //greet("Hello", "Jane")
    "Hello".greet("Jane")
}
